export const CHARACTERS = [
  {
    id: "coco",
    name: "Coco",
    title: "The Outsider Apprentice",
    hp: 100,
    power: 10,
    color: "#C97B4B",
    desc: "A girl born without magic who discovered the forbidden truth — that anyone can become a witch.",
    passive: "Drawing Prodigy: +10% accuracy bonus",
  },
  {
    id: "agott",
    name: "Agott",
    title: "The Prideful Prodigy",
    hp: 85,
    power: 13,
    color: "#7B68AE",
    desc: "A talented apprentice from a prestigious witch family, driven by pride and hidden insecurity.",
    passive: "Raw Power: +15% spell damage",
  },
  {
    id: "tetia",
    name: "Tetia",
    title: "The Gentle Heart",
    hp: 115,
    power: 8,
    color: "#E8A0BF",
    desc: "A kind-hearted apprentice whose gentle nature belies surprising resilience.",
    passive: "Mending Touch: +30% healing power",
  },
  {
    id: "richeh",
    name: "Richeh",
    title: "The Silent Scholar",
    hp: 95,
    power: 11,
    color: "#5B8C7A",
    desc: "A quiet, observant apprentice who speaks little but sees much.",
    passive: "Arcane Shield: +20% defense spells",
  },
];

export const SPELLS = [
  {
    id: "fireball",
    name: "Ignis Glyph",
    type: "attack",
    baseDmg: 25,
    icon: "🔥",
    desc: "A searing flame drawn from ember runes",
    difficulty: 1,
    sigilType: "circle_cross",
  },
  {
    id: "wind",
    name: "Sylph Sigil",
    type: "attack",
    baseDmg: 20,
    icon: "🌪️",
    desc: "Cutting winds traced in spiraling arcs",
    difficulty: 1,
    sigilType: "spiral",
  },
  {
    id: "light",
    name: "Lumen Arc",
    type: "attack",
    baseDmg: 35,
    icon: "✨",
    desc: "Blinding radiance from a perfect star glyph",
    difficulty: 3,
    sigilType: "star",
  },
  {
    id: "water",
    name: "Aqua Ring",
    type: "attack",
    baseDmg: 18,
    icon: "💧",
    desc: "Flowing water summoned by concentric rings",
    difficulty: 1,
    sigilType: "concentric",
  },
  {
    id: "shield",
    name: "Aegis Circle",
    type: "defense",
    baseShield: 20,
    icon: "🛡️",
    desc: "A protective barrier woven from ward glyphs",
    difficulty: 2,
    sigilType: "triangle_circle",
  },
  {
    id: "heal",
    name: "Vita Bloom",
    type: "heal",
    baseHeal: 22,
    icon: "🌿",
    desc: "Life energy channeled through nature runes",
    difficulty: 2,
    sigilType: "flower",
  },
];

export const ENEMY_DATA = {
  name: "Brimhat Sorcerer",
  hp: 100,
  power: 10,
  color: "#8B1A1A",
  spells: ["fireball", "wind", "water", "shield"],
};
